'use strict';
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const TEST_MODE = new URLSearchParams(location.search).get('verification') === '1';
const STORAGE_KEY = 'constat-field-visit' + PROFILE.suffix;
const state = {currentStep:1, activeSubject:'Vue générale', subjects:['Vue générale'], photos:[], position:null, actions:[], drawingTarget:null, caseIndex:0, draftId:null,dossierId:null,caseName:'',caseReference:'',visitDate:new Date().toLocaleDateString('en-CA'),caseType:'autre',hideNominatif:false};
// Champs du rapport HTML CDL EXPERT. En expertise judiciaire, les champs client ne sont jamais conservés (RGPD).
const ATTENDANCE_MAX=6;
const REPORT_TEXT_FIELDS=['siteAddress','presents','expertNote','clientName','clientAddress','missionDetail','conclusions'],CLIENT_FIELDS=['clientName','clientAddress'];
function resetReportFields(){state.caseType=PROFILE.defaultType;state.hideNominatif=false;state.pv=defaultPv();state.expertSigns=false;state.expertSignature=null;state.transferHash='';state.lastExport=null;state.closedAt='';state.attendance=[];for(const key of REPORT_TEXT_FIELDS)state[key]='';}
resetReportFields();
function reportFieldValue(key){return state.caseType==='ej'&&CLIENT_FIELDS.includes(key)?'':state[key]||'';}
const sidebar = $('.sidebar');
let ready=false, saveTimer, saveQueue=Promise.resolve(), revision=0, unsaved=false;
let pendingImports=0, pendingCapture=false;
let recording=null, audioTarget=null, cameraStream=null, cameraVersion=0;
const speechClass=window.SpeechRecognition || window.webkitSpeechRecognition;
const escapeHtml=(value='')=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const createId=()=>globalThis.crypto?.randomUUID?.() || `photo-${Date.now()}-${Math.random().toString(16).slice(2)}`;
function updateSaveState(message,error=false){$('.save-state').textContent=message;$('.save-state').classList.toggle('save-error',error);}
function tell(message){$('#capture-status').textContent=message;}
function showPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav-item').forEach(p=>p.classList.toggle('active',p.dataset.view===id));sidebar.classList.remove('open');window.scrollTo(0,0);}
function renderStep(){$$('.step-content').forEach(p=>p.classList.toggle('active',Number(p.dataset.step)===state.currentStep));$$('.step').forEach((p,i)=>p.classList.toggle('active',i<state.currentStep));if(state.currentStep===4)buildReportPreview();window.scrollTo(0,0);}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.view)));
$('.mobile-menu').addEventListener('click',()=>sidebar.classList.toggle('open'));
$$('.new-inspection').forEach(b=>b.addEventListener('click',()=>startNewVisit()));
$$('.resume').forEach(b=>b.addEventListener('click',()=>{state.currentStep=2;showPage('inspection');renderStep();}));
$$('.back-btn').forEach(b=>b.addEventListener('click',()=>showPage('dashboard')));
$$('.next-step').forEach(b=>b.addEventListener('click',()=>{if(recording){tell('Arrêtez la note vocale avant de poursuivre.');return;}state.currentStep=Math.min(4,state.currentStep+1);renderStep();}));
$$('.prev-step').forEach(b=>b.addEventListener('click',()=>{state.currentStep=Math.max(1,state.currentStep-1);renderStep();}));
function selectCase(index){state.caseIndex=index;$$('.case-option').forEach((p,i)=>{p.classList.toggle('selected',i===index);p.lastElementChild.textContent=i===index?'✓':'';});}
$$('.case-option').forEach((b,i)=>b.addEventListener('click',()=>{selectCase(i);state.caseName=b.querySelector('b').textContent;state.caseReference=b.querySelector('small').textContent;renderCaseDetails();saveVisit();}));
function renderCaseDetails(){for(const [id,key] of [['case-name','caseName'],['case-reference','caseReference'],['visit-date','visitDate']])$('#'+id).value=state[key]||'';if(typeof renderReportFields==='function')renderReportFields();}
for(const [id,key] of [['case-name','caseName'],['case-reference','caseReference'],['visit-date','visitDate']])$('#'+id).addEventListener('input',e=>{state[key]=e.target.value;saveVisit();});
function reportHeading(){return [state.caseReference,state.caseName||'Constat de terrain'].filter(Boolean).join(' — ');}
function addSubject(value){const name=value.trim().slice(0,160);if(!name)return null;const existing=state.subjects.find(s=>s.toLocaleLowerCase()===name.toLocaleLowerCase());if(existing)return existing;state.subjects.push(name);return name;}
function renderSubjects(){$('#subject-tabs').innerHTML=state.subjects.map((s,i)=>`<button data-subject-index="${i}" class="${s===state.activeSubject?'active':''}">${escapeHtml(s)} <span>(${state.photos.filter(p=>p.subject===s).length})</span></button>`).join('');$('#active-subject').textContent=`${state.activeSubject} — ${state.photos.filter(p=>p.subject===state.activeSubject).length} photo(s). Ajoutez autant de photos que nécessaire, puis choisissez un autre désordre pour continuer ce même constat.`;}
$('#subject-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-subject-index]');if(!b)return;state.activeSubject=state.subjects[Number(b.dataset.subjectIndex)];renderSubjects();renderCaptures();saveVisit();});
$('#subject-form').addEventListener('submit',e=>{e.preventDefault();const name=addSubject($('#subject-name').value);if(!name)return;state.activeSubject=name;$('#subject-name').value='';renderSubjects();renderCaptures();saveVisit();tell(`Sujet sélectionné : ${name}. Les photos des autres sujets sont conservées dans le même constat.`);});
function included(photo,field){return photo.include?.[field]!==false;}
function audioMarkup(photo){return photo.audio?`<audio controls preload="metadata" src="${escapeHtml(photo.audio)}"></audio><a download="note-photo-${photo.number}.${photo.audio.includes('audio/mp4')?'m4a':photo.audio.includes('audio/ogg')?'ogg':'webm'}" href="${escapeHtml(photo.audio)}">Télécharger l’audio de la photo ${photo.number}</a><button type="button" class="secondary danger delete-audio" data-delete-audio="${escapeHtml(photo.id)}">🗑 Supprimer l’enregistrement sonore</button>`:'<p class="muted">Aucun enregistrement sonore.</p>';}
// Suppression d'un enregistrement sonore devenu inutile (fiche de capture et synthèse).
document.addEventListener('click',e=>{const b=e.target.closest('[data-delete-audio]');if(!b)return;const photo=state.photos.find(p=>p.id===b.dataset.deleteAudio);if(!photo?.audio)return;
  if(recording){alert('Terminez l’enregistrement en cours.');return;}if(!confirm(`Supprimer l’enregistrement sonore de la photo ${photo.number} ?`))return;
  photo.audio=null;renderCaptures();if(state.currentStep===4)buildReportPreview();saveVisit();tell(`Enregistrement sonore de la photo ${photo.number} supprimé.`);});
function transcriptStatus(photo){return photo.transcriptStatus||(photo.transcript?'Texte à relire.':'Aucune transcription. Vous pouvez saisir ou coller le texte ci-dessous.');}
function renderCaptures(){
  const visible=state.photos.filter(p=>p.subject===state.activeSubject);
  $('#capture-list').innerHTML=visible.length?visible.map(photo=>`<article class="capture-card" data-photo-id="${photo.id}"><div class="photo-frame"><img src="${escapeHtml(photo.annotatedSrc||photo.src)}" alt="Photo ${photo.number}"><span>PHOTO ${photo.number}</span></div><div class="capture-fields">
  <label>Sujet de cette photo (désordre ou lieu)<select class="photo-subject" aria-label="Sujet de la photo ${photo.number}">${state.subjects.map(s=>`<option value="${escapeHtml(s)}" ${s===photo.subject?'selected':''}>${escapeHtml(s)}</option>`).join('')}<option value="__nouveau">＋ Nouveau sujet…</option></select></label>
  <label>Description<textarea data-edit="description">${escapeHtml(photo.description)}</textarea></label><button type="button" class="expand-text" data-command="expand" data-field="description">⤢ Écrire en grand</button><label>Commentaires / observations<textarea data-edit="comment">${escapeHtml(photo.comment)}</textarea></label><button type="button" class="expand-text" data-command="expand" data-field="comment">⤢ Écrire en grand</button>
  <div class="input-modes"><button class="secondary" data-command="annotate">Annoter la photo</button><button class="secondary" data-command="drawing">Écrire au stylet</button><button class="secondary" data-command="audio" ${recording?'disabled':''}>🎙 Dicter ou enregistrer un son</button></div>
  ${photo.drawing?`<figure class="handwriting"><figcaption>Note manuscrite — modifiable avec « Écrire au stylet »</figcaption><img src="${escapeHtml(photo.drawing)}" alt="Note manuscrite de la photo ${photo.number}"></figure>`:''}
  <section class="audio-note"><strong>Enregistrement sonore</strong>${audioMarkup(photo)}${photo.transcript?`<label>Transcription (ancienne note vocale)<textarea data-edit="transcript">${escapeHtml(photo.transcript)}</textarea></label>`:''}</section>
  <p class="photo-location">${locationLabel(photo)}</p><button class="secondary" data-command="locate">Associer la position actuelle à cette photo</button><button class="delete-photo" data-command="delete" ${recording?'disabled':''}>Supprimer la photo</button></div></article>`).join(''):'<div class="capture-empty"><h3>Aucune photo pour ce sujet</h3><p>Ouvrez l’appareil photo ou importez plusieurs photos.</p></div>';
}
$('#capture-list').addEventListener('input',e=>{const card=e.target.closest('[data-photo-id]');if(!card||!e.target.dataset.edit)return;const photo=state.photos.find(p=>p.id===card.dataset.photoId);photo[e.target.dataset.edit]=e.target.value;saveVisit();});
// Changer le sujet d'une photo : effet immédiat ; son numéro chronologique ne change pas.
$('#capture-list').addEventListener('change',e=>{if(!e.target.matches('.photo-subject'))return;const photo=state.photos.find(p=>p.id===e.target.closest('[data-photo-id]').dataset.photoId);if(!photo)return;
  let subject=e.target.value;if(subject==='__nouveau'){subject=addSubject(prompt('Nom du nouveau sujet (désordre ou lieu) :')||'');if(!subject){e.target.value=photo.subject;return;}}
  if(subject===photo.subject)return;photo.subject=subject;renderSubjects();renderCaptures();saveVisit();tell(`Photo ${photo.number} rattachée à « ${subject} ». Elle apparaît désormais dans ce sujet.`);});
$('#capture-list').addEventListener('click',async e=>{const b=e.target.closest('[data-command]');if(!b)return;const photo=state.photos.find(p=>p.id===b.closest('[data-photo-id]').dataset.photoId);if(!photo)return;
  switch(b.dataset.command){
    case 'annotate':openDrawing(photo.id,'photo');break;
    case 'drawing':openDrawing(photo.id);break;
    case 'expand':openTextEditor(photo,b.dataset.field);break;
    case 'audio':audioTarget=photo;$('#dictation-help').textContent=speechClass?'La dictée utilise la reconnaissance vocale du navigateur (souvent en ligne). Relisez le texte ajouté.':'Dictée indisponible dans ce navigateur : utilisez la touche micro du clavier dans le grand champ qui va s’ouvrir.';$('#audio-dialog').showModal();break;
    case 'locate':b.disabled=true;const position=await requestPosition();b.disabled=false;if(position){photo.position={...position,source:'manual'};renderCaptures();saveVisit();}else tell('Position indisponible. Vérifiez l’autorisation de localisation.');break;
    case 'delete':if(recording||!confirm(`Supprimer la photo ${photo.number} et ses notes ?`))return;state.photos=state.photos.filter(p=>p!==photo);renderSubjects();renderCaptures();saveVisit();break;
  }
});
function readBlob(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});}
function requestPosition(){startLocationWatch(true);return sessionPosition();}
function validPosition(p){return p&&Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&Math.abs(p.lat)<=90&&Math.abs(p.lng)<=180;}
function locationLabel(photo){const p=photo.position;if(!validPosition(p))return 'Aucune position associée à cette photo.';const source=p.source==='capture'?'Position relevée lors de la capture':p.source==='manual'?'Position associée manuellement':'Position de visite associée (lieu de prise de vue à vérifier)';return `${source} : ${p.lat.toFixed(6)}, ${p.lng.toFixed(6)}${Number.isFinite(p.accuracy)?` · précision ±${Math.round(p.accuracy)} m`:''}`;}
function showPosition(){const p=state.position;$('#geo-status small').textContent=validPosition(p)?`${p.lat.toFixed(6)}, ${p.lng.toFixed(6)} · précision ±${Math.round(p.accuracy||0)} m. Cette position ne modifie pas les anciennes photos.`:'Appuyez pour autoriser la géolocalisation';$('#geo-status').classList.toggle('located',!!p);}
$('#locate-button').addEventListener('click',async()=>{$('#geo-status small').textContent='Recherche de la position…';const p=await requestPosition();if(p){state.position=p;showPosition();saveVisit();}else $('#geo-status small').textContent='Position indisponible ou autorisation refusée.';});
function addPhoto(src,subject,capturedAt,position=null,captureSource='import'){const number=Math.max(0,...state.photos.map(p=>p.number))+1;state.photos.push({id:createId(),number,subject,src,description:'',comment:'',transcript:'',drawing:'',audio:null,capturedAt,captureSource,position,include:{description:true,comment:true,transcript:true,drawing:true}});renderSubjects();renderCaptures();saveVisit();}
async function compressPhoto(src){const image=await loadDrawingImage(src),scale=Math.min(1,1600/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',0.78);}
let importQueue=Promise.resolve();
async function importFiles(files,native=false,subject=state.activeSubject){const time=new Date().toISOString();const positionPromise=Promise.resolve(null);let failures=0;for(const file of files){if(!file.type.startsWith('image/')){failures++;continue;}try{const src=await compressPhoto(await readBlob(file));const position=await positionPromise;addPhoto(src,subject,time,position?{...position,source:'capture'}:null,native?'native-camera':'import');}catch{failures++;}}tell(`${files.length-failures} photo(s) ajoutée(s) et allégée(s) pour ${subject}.${failures?` ${failures} fichier(s) illisible(s) : utilisez JPEG ou PNG.`:''}${native?' Associez la position actuelle si vous êtes encore au lieu photographié.':' Les photos importées n’ont pas de position connue.'}`);}
$('#import-photo').addEventListener('click',()=>$('#photo-input').click());
for(const [selector,native] of [['#photo-input',false],['#native-camera',true]])$(selector).addEventListener('change',e=>{const files=[...e.target.files],subject=state.activeSubject;e.target.value='';pendingImports++;importQueue=importQueue.then(()=>importFiles(files,native,subject)).finally(()=>pendingImports--);});
function closeCamera(){++cameraVersion;cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;$('#camera-video').srcObject=null;}
$('#photo-button').addEventListener('click',async()=>{const version=++cameraVersion;$('#camera-dialog').showModal();$('#take-photo').disabled=true;$('#camera-status').textContent='Autorisez l’accès à la caméra dans le navigateur.';
  try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');const stream=await acquireVisitStream('video');if(version!==cameraVersion||!$('#camera-dialog').open){stream.getTracks().forEach(t=>t.stop());return;}cameraStream=stream;$('#camera-video').srcObject=stream;await $('#camera-video').play();if(version!==cameraVersion)return;$('#take-photo').disabled=false;$('#camera-status').textContent='Cadrez la photo, puis appuyez sur « Prendre la photo ».';}
  catch(error){console.warn('Caméra :',error);$('#camera-status').textContent='Caméra indisponible ou accès refusé. Sur téléphone, essayez le bouton ci-dessous. Sur ordinateur, vérifiez votre webcam ou utilisez « Importer des photos ».';}
});
$('#close-camera').addEventListener('click',()=>$('#camera-dialog').close());$('#camera-dialog').addEventListener('close',()=>{if(!$('#camera-dialog').open)closeCamera();});
$('#native-camera-button').addEventListener('click',()=>{closeCamera();$('#camera-dialog').close();$('#native-camera').click();});
$('#take-photo').addEventListener('click',async()=>{const video=$('#camera-video');if(!video.videoWidth)return;$('#take-photo').disabled=true;pendingCapture=true;const c=document.createElement('canvas');c.width=video.videoWidth;c.height=video.videoHeight;c.getContext('2d').drawImage(video,0,0);const raw=c.toDataURL('image/jpeg',0.92),subject=state.activeSubject,time=new Date().toISOString(),positionPromise=Promise.resolve(recentPosition(15000));$('#camera-dialog').close();tell('Photo prise. Réduction de taille et recherche de sa position…');try{const src=await compressPhoto(raw),position=await positionPromise;addPhoto(src,subject,time,position?{...position,source:'capture'}:null,'camera');tell(position?'Photo allégée et position ajoutées. Vous pouvez prendre la suivante pour ce même sujet.':'Photo allégée ajoutée sans position : localisation indisponible.');}catch{tell('La photo n’a pas pu être ajoutée. Réessayez.');}finally{pendingCapture=false;}});
$('#close-audio').addEventListener('click',()=>$('#audio-dialog').close());
function refreshTranscript(photo){$$('[data-photo-id]').filter(c=>c.dataset.photoId===photo.id).forEach(c=>{const field=c.querySelector('[data-edit="transcript"]');if(field&&document.activeElement!==field)field.value=photo.transcript||'';const status=c.querySelector('.transcript-status');if(status)status.textContent=transcriptStatus(photo);});}
// Deux usages distincts, jamais simultanés (sur iPad, dictée et enregistrement se disputent le micro et figeaient la page) :
// « Dicter » ajoute le texte reconnu aux commentaires ; « Enregistrer un son » conserve un fichier audio (bruit, ambiance).
const RECORD_LIMIT_MS=15*60*1000;
function showRecordingBar(text){$('#recording-status').hidden=false;$('#recording-label').textContent=text;$('#recording-live').textContent='';}
function hideRecordingBar(){$('#recording-status').hidden=true;clearInterval(recording?.timer);}
function recordingClock(session,label){const start=Date.now();session.timer=setInterval(()=>{const s=Math.floor((Date.now()-start)/1000);$('#recording-label').textContent=`${label} — ${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;if(Date.now()-start>RECORD_LIMIT_MS)stopRecording();},500);}
function finishRecording(message){const session=recording;if(!session)return;clearInterval(session.timer);clearTimeout(session.safety);session.stream?.getTracks().forEach(t=>t.stop());recording=null;hideRecordingBar();renderCaptures();saveVisit();if(message)tell(message);}
// Android (Chrome) coupe la reconnaissance après quelques secondes, souvent sans résultat « définitif » : on garde le texte
// provisoire et on relance l'écoute jusqu'à ce que l'utilisateur appuie sur « Arrêter » (ou la limite de 15 min).
const DICTATION_FATAL=['not-allowed','service-not-allowed','audio-capture','language-not-supported','network'];
function dictationCommit(session){if(session.segment){session.text=[session.text,session.segment].filter(Boolean).join(' ');session.segment='';}}
function startDictation(photo){
  if(!speechClass){openTextEditor(photo,'comment',true);return;}
  // Le micro gardé ouvert pour « Enregistrer un son » empêche la reconnaissance vocale d'Android de l'utiliser :
  // il est libéré ici et rouvert automatiquement au prochain enregistrement sonore.
  if(typeof visitAccess!=='undefined')visitAccess.tracks.filter(t=>t.kind==='audio').forEach(t=>t.stop());
  const session={kind:'dictation',photo,stopping:false,text:'',segment:'',quickEnds:0};recording=session;const label=`● Dictée — photo ${photo.number}`;showRecordingBar(label);recordingClock(session,label);renderCaptures();
  $('#recording-live').textContent='Parlez… L’écoute continue jusqu’à « Arrêter ».';
  const android=/Android/i.test(navigator.userAgent);
  const finish=()=>{dictationCommit(session);const text=session.text.trim();
    if(text){photo.comment=[photo.comment?.trim(),text].filter(Boolean).join('\n');photo.transcriptStatus='';}
    const why=session.error==='network'?'la reconnaissance vocale du navigateur nécessite une connexion Internet. Hors réseau, utilisez « Enregistrer un son » ou la touche micro du clavier':session.error==='not-allowed'||session.error==='service-not-allowed'?'micro refusé : autorisez-le dans les réglages du navigateur':session.error==='audio-capture'?'micro occupé ou indisponible : fermez les autres applications qui l’utilisent':session.error;
    finishRecording(text?`Dictée ajoutée aux commentaires de la photo ${photo.number}. Relisez-la.${why?' (Écoute interrompue : '+why+'.)':''}`:why?`Dictée interrompue : ${why}.`:'Aucun texte reconnu.');};
  const listen=()=>{const recognition=new speechClass(),started=Date.now();session.recognition=recognition;session.error='';
    recognition.lang='fr-FR';recognition.continuous=!android;recognition.interimResults=true;
    // Texte de la séquence en cours (résultats définitifs et provisoires), repris intégralement à chaque événement.
    recognition.onresult=e=>{session.segment=Array.from(e.results,r=>r[0]?.transcript.trim()||'').filter(Boolean).join(' ');$('#recording-live').textContent=[session.text,session.segment].filter(Boolean).join(' ');};
    recognition.onerror=e=>{session.error=e.error==='no-speech'||e.error==='aborted'?'':e.error;};
    recognition.onend=()=>{if(recording!==session)return;dictationCommit(session);
      if(!session.stopping&&!DICTATION_FATAL.includes(session.error)){session.quickEnds=Date.now()-started<1500?session.quickEnds+1:0;
        if(session.quickEnds<5){try{listen();return;}catch{}}}
      finish();};
    recognition.start();};
  try{listen();}catch{finishRecording('Dictée indisponible. Utilisez la touche micro du clavier dans le champ Commentaires.');}
}
async function startSoundRecording(photo){
  if(photo.audio&&!confirm('Remplacer l’enregistrement sonore existant de cette photo ?'))return;
  const session={kind:'sound',photo,stopping:false,stream:null,recorder:null};recording=session;showRecordingBar('Autorisation du microphone…');renderCaptures();
  try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('unsupported');
    const stream=await acquireVisitStream('audio');session.stream=stream;if(session.stopping){finishRecording();return;}
    const recorder=new MediaRecorder(stream);session.recorder=recorder;const chunks=[];
    recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
    recorder.onerror=()=>stopRecording();
    recorder.onstop=async()=>{if(recording!==session)return;
      try{const blob=new Blob(chunks,{type:recorder.mimeType||chunks[0]?.type||'audio/webm'});if(!blob.size)throw new Error('empty');photo.audio=await readBlob(blob);finishRecording(`Enregistrement sonore conservé pour la photo ${photo.number}.`);}
      catch{finishRecording('L’enregistrement n’a pas pu être conservé. Réessayez.');}};
    recorder.start(1000);recordingClock(session,`● Enregistrement sonore — photo ${photo.number}`);
  }catch{finishRecording('Microphone indisponible ou autorisation refusée. Vérifiez les réglages du navigateur (Réglages → Safari/Chrome → Microphone).');}
}
$('#start-dictation').addEventListener('click',()=>{const photo=audioTarget;$('#audio-dialog').close();if(!recording&&photo)startDictation(photo);});
$('#start-sound').addEventListener('click',()=>{const photo=audioTarget;$('#audio-dialog').close();if(!recording&&photo)startSoundRecording(photo);});
// Arrêt toujours possible : si le navigateur ne rend pas la main en 4 s, l'arrêt est forcé (pas de page figée).
function stopRecording(){const session=recording;if(!session||session.stopping)return;session.stopping=true;$('#recording-label').textContent='Finalisation…';
  try{if(session.kind==='dictation')session.recognition?.stop();else if(session.recorder?.state==='recording')session.recorder.stop();else finishRecording();}catch{finishRecording();}
  session.safety=setTimeout(()=>{if(recording!==session)return;try{session.recognition?.abort();}catch{}
    if(session.kind==='dictation'){dictationCommit(session);}
    if(session.kind==='dictation'&&session.text.trim()){session.photo.comment=[session.photo.comment?.trim(),session.text.trim()].filter(Boolean).join('\n');}
    finishRecording('Arrêt forcé : le navigateur ne répondait plus. Le texte ou le son déjà capté a été conservé si possible.');},4000);}
$('#stop-recording').addEventListener('click',stopRecording);
function addAction(values={}){const row=$('#action-template').content.firstElementChild.cloneNode(true);row.querySelector('select').value=values.type||'Créer une tâche';row.querySelector('.action-text').value=values.text||'';row.querySelector('.action-recipient').value=values.recipient||'';row.querySelector('[type="date"]').value=values.date||'';row.querySelector('.remove-action').addEventListener('click',()=>{row.remove();saveVisit();});row.addEventListener('input',saveVisit);$('#action-list').append(row);}
$('#add-action').addEventListener('click',()=>{addAction();saveVisit();});
function collectActions(){return $$('.action-row').map(row=>({type:row.querySelector('select').value,text:row.querySelector('.action-text').value,recipient:row.querySelector('.action-recipient').value,date:row.querySelector('[type="date"]').value}));}
function checkField(photo,field,label,body){return `<section class="review-field"><label class="check-label"><input type="checkbox" data-include="${field}" ${included(photo,field)?'checked':''}> Inclure ${label} dans l’export</label>${body}</section>`;}
function buildReportPreview(){
  $('#summary-editor').innerHTML=state.photos.map(p=>`<article class="summary-card" data-photo-id="${p.id}"><h3>Photo ${p.number} — ${escapeHtml(p.subject)}</h3>${checkField(p,'description','la description',`<label>Description<textarea data-edit="description">${escapeHtml(p.description)}</textarea></label><button type="button" class="expand-text" data-field="description">⤢ Écrire en grand</button>`)}${checkField(p,'comment','les commentaires',`<label>Commentaires modifiables<textarea data-edit="comment">${escapeHtml(p.comment)}</textarea></label><button type="button" class="expand-text" data-field="comment">⤢ Écrire en grand</button>`)}${checkField(p,'transcript','la transcription',`<p class="transcript-status">${escapeHtml(transcriptStatus(p))}</p><label>Transcription modifiable<textarea data-edit="transcript">${escapeHtml(p.transcript)}</textarea></label>`)}${p.drawing?checkField(p,'drawing','la note manuscrite',`<img class="handwriting-preview" src="${escapeHtml(p.drawing)}" alt="Note manuscrite">`):''}<section class="audio-note"><strong>Audio de la photo ${p.number} — écoute et téléchargement séparé</strong>${audioMarkup(p)}</section></article>`).join('');
  updateReportContent();renderMap();
}
$('#summary-editor').addEventListener('input',e=>{const card=e.target.closest('[data-photo-id]');if(!card)return;const photo=state.photos.find(p=>p.id===card.dataset.photoId);if(e.target.dataset.edit)photo[e.target.dataset.edit]=e.target.value;if(e.target.dataset.include){photo.include||={};photo.include[e.target.dataset.include]=e.target.checked;}updateReportContent();saveVisit();});
function reportPhotoHtml(photo){const text=(field,label)=>included(photo,field)&&photo[field]?.trim()?`<p><strong>${label}</strong><br>${escapeHtml(photo[field]).replace(/\n/g,'<br>')}</p>`:'';return `<article><div class="report-image"><img src="${escapeHtml(photo.reportSrc||photo.annotatedSrc||photo.src)}" width="240" height="125" style="width:240px;height:125px;object-fit:contain" alt="Photo ${photo.number}"></div><h4>Photo ${photo.number}</h4>${text('description','Description')}${text('comment','Commentaires')}${text('transcript','Transcription')}${included(photo,'drawing')&&photo.drawing?`<img class="report-drawing" src="${escapeHtml(photo.drawing)}" width="240" style="width:240px;height:auto" alt="Note manuscrite">`:''}</article>`;}
function groupedReportHtml(){return state.subjects.map(subject=>{const photos=state.photos.filter(p=>p.subject===subject);if(!photos.length)return '';const rows=[];for(let i=0;i<photos.length;i+=2)rows.push(`<tr><td width="50%">${reportPhotoHtml(photos[i])}</td><td width="50%">${photos[i+1]?reportPhotoHtml(photos[i+1]):''}</td></tr>`);return `<section class="report-subject"><h3>${escapeHtml(subject)} — ${photos.length} photo(s)</h3><table class="report-table" width="100%"><tbody>${rows.join('')}</tbody></table></section>`;}).join('');}
function reportActionsHtml(){const actions=collectActions().filter(a=>a.text.trim()||a.recipient.trim());return actions.length?`<h3>Suites à donner</h3><ul>${actions.map(a=>`<li><strong>${escapeHtml(a.type)}</strong> — ${escapeHtml(a.text)}${a.recipient?` · Destinataire : ${escapeHtml(a.recipient)}`:''}${a.date?` · Échéance : ${escapeHtml(a.date)}`:''}</li>`).join('')}</ul>`:'';}
function updateReportContent(){$('#report-date').textContent=state.visitDate||'';$('.report-top small').textContent=reportHeading();$('#report-photos').innerHTML=groupedReportHtml()||'<p>Aucune photo.</p>';$('#report-actions').innerHTML=reportActionsHtml();}
function osmLink(p){return `https://www.openstreetmap.org/?mlat=${p.lat}&mlon=${p.lng}#map=18/${p.lat}/${p.lng}`;}
function renderMap(){const points=state.photos.filter(p=>validPosition(p.position)),visit=validPosition(state.position);if(!points.length&&!visit){$('#map-points').innerHTML='<p>Aucune photo localisée. Dans la collecte, utilisez « Associer la position actuelle à cette photo » si vous êtes sur place.</p>';return;}$('#map-points').innerHTML=`<label>Emplacement affiché<select id="map-selection">${points.map(p=>`<option value="${p.id}">Photo ${p.number} — ${escapeHtml(p.subject)}</option>`).join('')}${visit?'<option value="visit">Position de la visite (pas une prise de vue)</option>':''}</select></label><p id="map-caption"></p><iframe id="osm-map" title="Carte OpenStreetMap de l’emplacement sélectionné" loading="lazy"></iframe><a id="osm-link" target="_blank" rel="noopener">Ouvrir cette position dans OpenStreetMap</a><p>© contributeurs OpenStreetMap · Un repère à la fois ; changez de photo dans la liste.</p>`;$('#map-selection').addEventListener('change',updateMap);updateMap();}
function updateMap(){const choice=$('#map-selection').value,photo=state.photos.find(p=>p.id===choice),p=photo?.position||state.position,delta=0.002;const bbox=[Math.max(-180,p.lng-delta),Math.max(-90,p.lat-delta),Math.min(180,p.lng+delta),Math.min(90,p.lat+delta)].join(',');$('#osm-map').src=`https://www.openstreetmap.org/export/embed.html?bbox=${encodeURIComponent(bbox)}&layer=mapnik&marker=${p.lat}%2C${p.lng}`;$('#osm-link').href=osmLink(p);$('#map-caption').textContent=photo?`Photo ${photo.number} — ${locationLabel(photo)}`:'Position de visite uniquement. Elle n’est pas attribuée automatiquement aux photos importées.';}
function reportLocationsHtml(){const points=state.photos.filter(p=>validPosition(p.position));return points.length?`<h3>Emplacements des prises de vue</h3><ul>${points.map(p=>`<li>Photo ${p.number} — ${escapeHtml(locationLabel(p))} — <a href="${osmLink(p.position)}">Voir sur OpenStreetMap</a></li>`).join('')}</ul>`:'<p>Aucune position de prise de vue enregistrée.</p>';}
function exportBaseName(){return reportFileName(state.caseReference,state.visitDate).replace(/\.html$/,'');}
function saveFile(blob,name){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
// Enregistrement des rapports : pas de téléchargement « à l'aveugle ».
// - Ordinateur (Chrome, Edge) : l'explorateur s'ouvre pour choisir le dossier (OneDrive de l'expertise) ; il est
//   ensuite proposé d'office pour la même référence (mémoire du navigateur par expertise).
// - iPad, téléphone : menu de partage du système → « Enregistrer dans Fichiers » (OneDrive), Outlook, Gmail…
// - Sinon : téléchargement classique. Le constat note le dernier fichier réellement enregistré ou partagé.
const TOUCH_DEVICE=navigator.maxTouchPoints>0&&!/Windows/.test(navigator.userAgent);
const PICKER_TYPES={html:['text/html','Page HTML'],pdf:['application/pdf','Document PDF'],docx:['application/vnd.openxmlformats-officedocument.wordprocessingml.document','Document Word'],json:['application/json','Sauvegarde du constat'],jpg:['image/jpeg','Image JPEG']};
let sharedFiles=[];
function pickerId(){return ('exp-'+String(state.caseReference||'constats').trim()).replace(/[^\w-]+/g,'-').slice(0,32);}
// À appeler au clic, avant de préparer le fichier (l'explorateur exige un geste récent de l'utilisateur).
async function chooseSaveTarget(name){if(TOUCH_DEVICE||typeof window.showSaveFilePicker!=='function')return null;
  const ext=name.split('.').pop().toLowerCase(),type=PICKER_TYPES[ext];
  try{return await window.showSaveFilePicker({suggestedName:name,id:pickerId(),startIn:'documents',...(type?{types:[{description:type[1],accept:{[type[0]]:['.'+ext]}}]}:{})});}
  catch(error){return error?.name==='AbortError'?'cancel':null;}}
function noteExport(name){if(/\.(html|pdf|docx|json)$/i.test(name)){state.lastExport={name:String(name).slice(0,200),at:new Date().toISOString()};saveVisit();if(typeof renderCloseStatus==='function')renderCloseStatus();}}
function canShareFiles(files){try{return !!(files.length&&files.every(Boolean)&&navigator.canShare?.({files}));}catch{return false;}}
// Renvoie true quand le fichier est enregistré (ou remis au menu de partage), false s'il reste à enregistrer.
async function download(blob,name,options={}){
  let target=options.target;if(target===undefined&&!options.append)target=await chooseSaveTarget(name);
  if(target==='cancel')return false;
  if(target){try{const writable=await target.createWritable();await writable.write(blob);await writable.close();noteExport(name);showShareBar(`« ${target.name||name} » enregistré dans le dossier choisi.`,false);return true;}catch(error){console.error(error);}}
  const file=typeof File==='function'?new File([blob],name,{type:blob.type||'application/octet-stream'}):null;
  if(TOUCH_DEVICE&&canShareFiles([file])){
    if(options.append){sharedFiles=[...sharedFiles,file];showShareBar(`${sharedFiles.length} fichier(s) prêt(s).`,true);return false;}
    sharedFiles=[file];
    try{await navigator.share({files:[file],title:name});noteExport(name);$('#share-bar').hidden=true;return true;}
    catch(error){showShareBar(`« ${name} » est prêt. Touchez « Enregistrer… » puis « Enregistrer dans Fichiers » (OneDrive) ou votre messagerie.`,true);return false;}}
  saveFile(blob,name);noteExport(name);sharedFiles=[file];
  showShareBar(`« ${name} » enregistré dans les Téléchargements de l’appareil.`,canShareFiles([file]));return true;}
function showShareBar(text,share){const bar=$('#share-bar');if(!bar)return;$('#share-text').textContent=text;$('#share-file').hidden=!share;$('#share-download').hidden=!share;bar.hidden=false;}
$('#share-file').addEventListener('click',async()=>{const files=sharedFiles.filter(Boolean);if(!canShareFiles(files))return;
  try{await navigator.share({files,title:files[0].name});files.forEach(f=>noteExport(f.name));$('#share-bar').hidden=true;}catch(error){if(error?.name!=='AbortError')alert('Menu d’enregistrement indisponible : utilisez « Télécharger ».');}});
$('#share-download').addEventListener('click',()=>{for(const file of sharedFiles.filter(Boolean)){saveFile(file,file.name);noteExport(file.name);}showShareBar('Fichier(s) enregistré(s) dans les Téléchargements de l’appareil.',false);});
$('#share-close').addEventListener('click',()=>{$('#share-bar').hidden=true;});
$('#generate-report').addEventListener('click',async()=>{
  if(visitBusy()){alert('Terminez la capture avant de créer le rapport.');return;}
  if(!state.photos.length){alert('Ajoutez au moins une photo au constat.');return;}
  const name=exportBaseName()+'_reportage-photographique.docx',target=await chooseSaveTarget(name);if(target==='cancel')return;
  const button=$('#generate-report');button.disabled=true;
  try{updateReportContent();const photos=structuredClone(state.photos);for(const p of photos){const image=await loadDrawingImage(p.annotatedSrc||p.src);p.imageWidth=image.naturalWidth;p.imageHeight=image.naturalHeight;if(p.drawing){const note=await loadDrawingImage(p.drawing);p.noteWidth=note.naturalWidth;p.noteHeight=note.naturalHeight;}}
    const blob=await buildConstatWord({photos,subjects:[...state.subjects],actions:collectActions(),heading:reportHeading(),date:state.visitDate});
    if(await download(blob,name,{target}))$('.toast').textContent='Rapport Word enregistré (.docx).';else return;$('.toast').classList.add('show');setTimeout(()=>$('.toast').classList.remove('show'),4000);
  }catch(error){console.error(error);alert('Le rapport Word n’a pas pu être créé. Vérifiez les photos et réessayez.');}finally{button.disabled=false;}
});
const database=new Promise(resolve=>{if(!window.indexedDB||PROFILE.pending){resolve(null);return;}try{const req=indexedDB.open('constat-visits'+PROFILE.suffix,2);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('visits'))req.result.createObjectStore('visits');if(!req.result.objectStoreNames.contains('drafts'))req.result.createObjectStore('drafts');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null);req.onblocked=()=>resolve(null);}catch{resolve(null);}});
async function dbRead(){const db=await database;if(!db)return null;return new Promise((resolve,reject)=>{const request=db.transaction('visits').objectStore('visits').get('current');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function dbWrite(value){const db=await database;if(!db){localStorage.setItem(STORAGE_KEY,JSON.stringify(value));localStorage.setItem(STORAGE_KEY+'-draft-'+value.draftId,JSON.stringify(value));return;}return new Promise((resolve,reject)=>{const tx=db.transaction(['visits','drafts'],'readwrite');tx.objectStore('visits').put(value,'current');tx.objectStore('drafts').put(value,value.draftId);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function snapshot(){state.draftId||=createId();return {version:2,draftId:state.draftId,savedAt:new Date().toISOString(),subjects:[...state.subjects],activeSubject:state.activeSubject,photos:structuredClone(state.photos).map(p=>{delete p.reportSrc;return p;}),position:state.position,actions:collectActions(),caseIndex:state.caseIndex,dossierId:state.dossierId,dossier:dossierById(state.dossierId),caseName:state.caseName,caseReference:state.caseReference,visitDate:state.visitDate,caseType:state.caseType,hideNominatif:!!state.hideNominatif,pv:state.caseType==='ep'?structuredClone(state.pv):defaultPv(),expertSigns:!!state.expertSigns,expertSignature:state.expertSignature,transferHash:state.transferHash||'',lastExport:state.lastExport||null,closedAt:state.closedAt||'',attendance:[...(state.attendance||[])],...Object.fromEntries(REPORT_TEXT_FIELDS.map(key=>[key,reportFieldValue(key)]))};}
function saveVisit(){if(!ready)return;unsaved=true;++revision;updateSaveState('Enregistrement…');clearTimeout(saveTimer);saveTimer=setTimeout(persistVisit,300);}
function persistVisit(){if(!ready)return Promise.resolve();clearTimeout(saveTimer);const version=revision,value=snapshot();saveQueue=saveQueue.catch(()=>{}).then(()=>dbWrite(value)).then(()=>{if(version===revision){unsaved=false;updateSaveState('✓ Brouillon enregistré sur cet appareil');}renderDrafts();return true;}).catch(()=>{updateSaveState('Échec de sauvegarde : conservez une copie avec « Sauvegarder la visite dans un fichier ».',true);return false;});return saveQueue;}
function normalizeVisit(saved){if(!saved||!Array.isArray(saved.photos)||!Array.isArray(saved.subjects))throw new Error('invalid');const result={...saved,subjects:[...new Set(saved.subjects.filter(s=>typeof s==='string'&&s.trim()).map(s=>s.slice(0,160)))]};if(!result.subjects.length)result.subjects=['Vue générale'];const ids=new Set(),numbers=new Set();result.photos=saved.photos.map((p,i)=>{if(!p||typeof p.src!=='string'||!/^data:image\/(jpeg|png|webp|gif|bmp|avif);/i.test(p.src))throw new Error('invalid image');const photo={id:typeof p.id==='string'&&/^[\w-]+$/.test(p.id)&&!ids.has(p.id)?p.id:createId(),number:Number.isInteger(p.number)&&p.number>0&&!numbers.has(p.number)?p.number:i+1,src:p.src,subject:typeof p.subject==='string'?p.subject.slice(0,160):result.subjects[0],position:validPosition(p.position)?p.position:null,capturedAt:p.capturedAt,captureSource:p.captureSource,include:{...p.include}};while(numbers.has(photo.number))photo.number++;ids.add(photo.id);numbers.add(photo.number);for(const key of ['description','comment','transcript','transcriptStatus'])photo[key]=typeof p[key]==='string'?p[key]:'';for(const key of ['drawing','annotatedSrc'])photo[key]=typeof p[key]==='string'&&/^data:image\/(jpeg|png|webp);/i.test(p[key])?p[key]:'';photo.audio=typeof p.audio==='string'&&/^data:(audio\/|video\/webm)/i.test(p.audio)?p.audio:null;if(!result.subjects.includes(photo.subject))result.subjects.push(photo.subject);return photo;});result.position=validPosition(saved.position)?saved.position:null;result.actions=Array.isArray(saved.actions)?saved.actions.filter(a=>a&&typeof a==='object').map(a=>Object.fromEntries(['type','text','recipient','date'].map(key=>[key,typeof a[key]==='string'?a[key]:'']))):[];return result;}
function restoreState(value){const saved=normalizeVisit(value);state.draftId=typeof saved.draftId==='string'?saved.draftId:createId();state.subjects=saved.subjects;state.activeSubject=state.subjects.includes(saved.activeSubject)?saved.activeSubject:state.subjects[0];state.photos=saved.photos;state.position=saved.position;state.caseName=typeof saved.caseName==='string'?saved.caseName:caseTitle(saved.caseIndex);state.caseReference=typeof saved.caseReference==='string'?saved.caseReference:'';state.visitDate=/^\d{4}-\d{2}-\d{2}$/.test(saved.visitDate)?saved.visitDate:(saved.savedAt||new Date().toISOString()).slice(0,10);state.dossierId=typeof saved.dossierId==='string'&&dossierById(saved.dossierId)?saved.dossierId:null;state.caseType=REPORT_TYPES[saved.caseType]?saved.caseType:state.dossierId?reportTypeOf(dossierById(state.dossierId).type):'autre';state.hideNominatif=saved.hideNominatif===true;state.pv=state.caseType==='ep'?normalizePv(saved.pv):defaultPv();state.expertSigns=saved.expertSigns===true;state.expertSignature=reportSignatureImage(saved.expertSignature)?{image:saved.expertSignature.image,at:String(saved.expertSignature.at||'').slice(0,40),name:String(saved.expertSignature.name||'').slice(0,200)}:null;state.transferHash=typeof saved.transferHash==='string'?saved.transferHash.slice(0,20):'';state.lastExport=saved.lastExport&&typeof saved.lastExport.name==='string'?{name:saved.lastExport.name.slice(0,200),at:String(saved.lastExport.at||'').slice(0,40)}:null;state.closedAt=typeof saved.closedAt==='string'?saved.closedAt.slice(0,40):'';state.attendance=Array.isArray(saved.attendance)?saved.attendance.filter(reportImage).slice(0,ATTENDANCE_MAX):[];for(const key of REPORT_TEXT_FIELDS)state[key]=typeof saved[key]==='string'?saved[key].slice(0,4000):'';for(const key of REPORT_TEXT_FIELDS)state[key]=reportFieldValue(key);syncDossierPicker();renderCaseDetails();selectCase(Number.isInteger(saved.caseIndex)&&saved.caseIndex>=0&&saved.caseIndex<$$('.case-option').length?saved.caseIndex:0);$('#action-list').innerHTML='';saved.actions.forEach(addAction);if(!$('.action-row'))addAction();renderSubjects();renderCaptures();showPosition();if(state.currentStep===4)buildReportPreview();}
$('#backup-visit').addEventListener('click',async()=>{if(visitBusy()){alert('Terminez la capture ou l’import avant de sauvegarder la visite.');return;}if(await download(new Blob([JSON.stringify(snapshot())],{type:'application/json'}),exportBaseName()+'_sauvegarde.json')&&typeof markTransferred==='function')markTransferred();});
$('#restore-visit').addEventListener('click',()=>{if(visitBusy()){alert('Terminez la capture ou l’import avant d’ouvrir une autre visite.');return;}$('#backup-input').click();});
$('#backup-input').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(visitBusy()){alert('Terminez la capture ou l’import avant de changer de visite.');return;}try{const saved=normalizeVisit(JSON.parse(await file.text()));if(state.photos.length&&!confirm('Remplacer la visite affichée par cette sauvegarde ? Conservez d’abord une copie si nécessaire.'))return;visitSwitching=true;try{if(!(await persistVisit()))return;suspendVisitAccess();if(saved.dossier)importDossier(saved.dossier);restoreState(saved);saveVisit();}finally{visitSwitching=false;}}catch{alert('Ce fichier n’est pas une sauvegarde Constat valide. La visite actuelle est conservée.');}});
window.addEventListener('beforeunload',e=>{if(unsaved||recording||pendingImports||pendingCapture){e.preventDefault();e.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&unsaved)persistVisit();});
async function initialize(){if(PROFILE.pending)return;document.body.classList.add('loading-visit');await LEGACY_IMPORT;let saved,restored=false;try{saved=await dbRead();if(!saved){const legacy=localStorage.getItem(STORAGE_KEY);if(legacy)saved=JSON.parse(legacy);}if(saved){restoreState(saved);restored=true;updateSaveState('✓ Visite restaurée sur cet appareil');}}catch{updateSaveState('La sauvegarde n’a pas pu être lue. Conservez votre ancienne version.',true);}finally{if(!$('.action-row'))addAction();renderSubjects();renderCaptures();showPosition();ready=true;renderCaseDetails();document.body.classList.remove('loading-visit');if(restored)saveVisit();renderDrafts();}}

// Grand cadre d'écriture (stylet, clavier ou dictée du clavier) pour la description et les commentaires.
const TEXT_LABELS={description:'Description',comment:'Commentaires / observations',transcript:'Transcription'};let textTarget=null;
function openTextEditor(photo,field,dictationFallback=false){textTarget={photo,field};$('#text-dialog-title').textContent=`${TEXT_LABELS[field]} — photo ${photo.number}`;const area=$('#text-dialog-field');area.value=photo[field]||'';
  $('.text-dialog-help').textContent=dictationFallback?'Dictée intégrée indisponible dans ce navigateur : touchez la touche micro du clavier pour dicter, puis Valider.':'Écrivez au stylet directement dans le cadre (Apple Pencil : écriture manuscrite convertie en texte), au clavier, ou avec la touche micro du clavier.';
  $('#text-dialog').showModal();area.focus();area.setSelectionRange(area.value.length,area.value.length);}
$('#save-text').addEventListener('click',()=>{if(!textTarget)return;textTarget.photo[textTarget.field]=$('#text-dialog-field').value;$('#text-dialog').close();renderCaptures();if(state.currentStep===4)buildReportPreview();saveVisit();});
for(const id of ['#cancel-text','#close-text'])$(id).addEventListener('click',()=>$('#text-dialog').close());
$('#text-dialog').addEventListener('close',()=>{textTarget=null;});
$('#summary-editor').addEventListener('click',e=>{const b=e.target.closest('.expand-text');if(!b)return;const photo=state.photos.find(p=>p.id===b.closest('[data-photo-id]').dataset.photoId);if(photo)openTextEditor(photo,b.dataset.field);});
