'use strict';
const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const TEST_MODE = new URLSearchParams(location.search).get('verification') === '1';
const STORAGE_KEY = 'constat-field-visit' + (TEST_MODE ? '-verification' : '');
const state = {currentStep:1, activeSubject:'Vue générale', subjects:['Vue générale'], photos:[], position:null, actions:[], drawingTarget:null, caseIndex:0, draftId:null};
const sidebar = $('.sidebar');
let ready=false, saveTimer, saveQueue=Promise.resolve(), revision=0, unsaved=false;
let pendingImports=0, pendingCapture=false;
let recording=null, audioTarget=null, cameraStream=null, cameraVersion=0;
const speechClass=window.SpeechRecognition || window.webkitSpeechRecognition;
const escapeHtml=(value='')=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const createId=()=>globalThis.crypto?.randomUUID?.() || `photo-${Date.now()}-${Math.random().toString(16).slice(2)}`;
function updateSaveState(message,error=false){$('.save-state').textContent=message;$('.save-state').classList.toggle('save-error',error);}
function tell(message){$('#capture-status').textContent=message;}
function showPage(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav-item').forEach(p=>p.classList.toggle('active',p.dataset.view===id));sidebar.classList.remove('open');window.scrollTo(0,0);}
function renderStep(){$$('.step-content').forEach(p=>p.classList.toggle('active',Number(p.dataset.step)===state.currentStep));$$('.step').forEach((p,i)=>p.classList.toggle('active',i<state.currentStep));if(state.currentStep===4)buildReportPreview();window.scrollTo(0,0);}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.view)));
$('.mobile-menu').addEventListener('click',()=>sidebar.classList.toggle('open'));
$$('.new-inspection').forEach(b=>b.addEventListener('click',()=>startNewVisit()));
$$('.resume').forEach(b=>b.addEventListener('click',()=>{state.currentStep=2;showPage('inspection');renderStep();}));
$$('.back-btn').forEach(b=>b.addEventListener('click',()=>showPage('dashboard')));
$$('.next-step').forEach(b=>b.addEventListener('click',()=>{if(recording){tell('Arrêtez la note vocale avant de poursuivre.');return;}state.currentStep=Math.min(4,state.currentStep+1);renderStep();}));
$$('.prev-step').forEach(b=>b.addEventListener('click',()=>{state.currentStep=Math.max(1,state.currentStep-1);renderStep();}));
function selectCase(index){state.caseIndex=index;$$('.case-option').forEach((p,i)=>{p.classList.toggle('selected',i===index);p.lastElementChild.textContent=i===index?'✓':'';});}
$$('.case-option').forEach((b,i)=>b.addEventListener('click',()=>{selectCase(i);saveVisit();}));
function addSubject(value){const name=value.trim().slice(0,160);if(!name)return null;const existing=state.subjects.find(s=>s.toLocaleLowerCase()===name.toLocaleLowerCase());if(existing)return existing;state.subjects.push(name);return name;}
function renderSubjects(){$('#subject-tabs').innerHTML=state.subjects.map((s,i)=>`<button data-subject-index="${i}" class="${s===state.activeSubject?'active':''}">${escapeHtml(s)} <span>(${state.photos.filter(p=>p.subject===s).length})</span></button>`).join('');$('#active-subject').textContent=`${state.activeSubject} — ${state.photos.filter(p=>p.subject===state.activeSubject).length} photo(s). Ajoutez autant de photos que nécessaire, puis choisissez un autre désordre pour continuer ce même constat.`;}
$('#subject-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-subject-index]');if(!b)return;state.activeSubject=state.subjects[Number(b.dataset.subjectIndex)];renderSubjects();renderCaptures();saveVisit();});
$('#subject-form').addEventListener('submit',e=>{e.preventDefault();const name=addSubject($('#subject-name').value);if(!name)return;state.activeSubject=name;$('#subject-name').value='';renderSubjects();renderCaptures();saveVisit();tell(`Sujet sélectionné : ${name}. Les photos des autres sujets sont conservées dans le même constat.`);});
function included(photo,field){return photo.include?.[field]!==false;}
function audioMarkup(photo){return photo.audio?`<audio controls preload="metadata" src="${escapeHtml(photo.audio)}"></audio><a download="note-photo-${photo.number}.${photo.audio.includes('audio/mp4')?'m4a':photo.audio.includes('audio/ogg')?'ogg':'webm'}" href="${escapeHtml(photo.audio)}">Télécharger l’audio de la photo ${photo.number}</a>`:'<p class="muted">Aucun audio enregistré.</p>';}
function transcriptStatus(photo){return photo.transcriptStatus||(photo.transcript?'Texte à relire.':'Aucune transcription. Vous pouvez saisir ou coller le texte ci-dessous.');}
function renderCaptures(){
  const visible=state.photos.filter(p=>p.subject===state.activeSubject);
  $('#capture-list').innerHTML=visible.length?visible.map(photo=>`<article class="capture-card" data-photo-id="${photo.id}"><div class="photo-frame"><img src="${escapeHtml(photo.annotatedSrc||photo.src)}" alt="Photo ${photo.number}"><span>PHOTO ${photo.number}</span></div><div class="capture-fields">
  <label>Désordre ou lieu<input class="photo-subject-name" value="${escapeHtml(photo.subject)}" list="subject-options" maxlength="160"></label><button class="secondary subject-apply" data-command="subject">Valider le rattachement</button>
  <label>Description<textarea data-edit="description">${escapeHtml(photo.description)}</textarea></label><label>Commentaires / observations<textarea data-edit="comment">${escapeHtml(photo.comment)}</textarea></label>
  <div class="input-modes"><button class="secondary" data-command="annotate">Annoter la photo</button><button class="secondary" data-command="drawing">Écrire au stylet</button><button class="secondary" data-command="audio" ${recording?'disabled':''}>Enregistrer une note vocale</button></div>
  ${photo.drawing?`<figure class="handwriting"><figcaption>Note manuscrite — modifiable avec « Écrire au stylet »</figcaption><img src="${escapeHtml(photo.drawing)}" alt="Note manuscrite de la photo ${photo.number}"></figure>`:''}
  <section class="audio-note"><strong>Note vocale</strong>${audioMarkup(photo)}<p class="transcript-status">${escapeHtml(transcriptStatus(photo))}</p><label>Transcription modifiable<textarea data-edit="transcript" placeholder="Texte reconnu pendant la dictée ou texte à saisir…">${escapeHtml(photo.transcript)}</textarea></label></section>
  <p class="photo-location">${locationLabel(photo)}</p><button class="secondary" data-command="locate">Associer la position actuelle à cette photo</button><button class="delete-photo" data-command="delete" ${recording?'disabled':''}>Supprimer la photo</button></div></article>`).join(''):'<div class="capture-empty"><h3>Aucune photo pour ce sujet</h3><p>Ouvrez l’appareil photo ou importez plusieurs photos.</p></div>';
  let list=$('#subject-options');if(!list){list=document.createElement('datalist');list.id='subject-options';document.body.append(list);}list.innerHTML=state.subjects.map(s=>`<option value="${escapeHtml(s)}">`).join('');
}
$('#capture-list').addEventListener('input',e=>{const card=e.target.closest('[data-photo-id]');if(!card||!e.target.dataset.edit)return;const photo=state.photos.find(p=>p.id===card.dataset.photoId);photo[e.target.dataset.edit]=e.target.value;saveVisit();});
$('#capture-list').addEventListener('change',e=>{if(!e.target.matches('.photo-subject-name'))return;const photo=state.photos.find(p=>p.id===e.target.closest('[data-photo-id]').dataset.photoId);const subject=addSubject(e.target.value);if(!subject){e.target.value=photo.subject;return;}photo.subject=subject;state.activeSubject=subject;renderSubjects();renderCaptures();saveVisit();});
$('#capture-list').addEventListener('click',async e=>{const b=e.target.closest('[data-command]');if(!b)return;const photo=state.photos.find(p=>p.id===b.closest('[data-photo-id]').dataset.photoId);if(!photo)return;
  switch(b.dataset.command){
    case 'subject':const subject=addSubject(b.closest('[data-photo-id]').querySelector('.photo-subject-name').value);if(subject){photo.subject=subject;state.activeSubject=subject;renderSubjects();renderCaptures();saveVisit();}break;
    case 'annotate':openDrawing(photo.id,'photo');break;
    case 'drawing':openDrawing(photo.id);break;
    case 'audio':audioTarget=photo;$('#transcribe-audio').disabled=!speechClass;$('#transcribe-audio').checked=!!speechClass;$('#speech-help').textContent=speechClass?'La transcription dépend du navigateur et peut envoyer la voix à son service en ligne. Relisez le texte obtenu. Un ancien audio ne peut pas être transcrit ici.':'Ce navigateur ne propose pas la transcription vocale. Vous pourrez écouter l’audio et saisir le texte.';$('#audio-dialog').showModal();break;
    case 'locate':b.disabled=true;const position=await requestPosition();b.disabled=false;if(position){photo.position={...position,source:'manual'};renderCaptures();saveVisit();}else tell('Position indisponible. Vérifiez l’autorisation de localisation.');break;
    case 'delete':if(recording||!confirm(`Supprimer la photo ${photo.number} et ses notes ?`))return;state.photos=state.photos.filter(p=>p!==photo);renderSubjects();renderCaptures();saveVisit();break;
  }
});
function readBlob(blob){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});}
function requestPosition(){return new Promise(resolve=>{if(!navigator.geolocation){resolve(null);return;}navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,measuredAt:new Date(p.timestamp).toISOString()}),()=>resolve(null),{enableHighAccuracy:true,maximumAge:0,timeout:10000});});}
function validPosition(p){return p&&Number.isFinite(p.lat)&&Number.isFinite(p.lng)&&Math.abs(p.lat)<=90&&Math.abs(p.lng)<=180;}
function locationLabel(photo){const p=photo.position;if(!validPosition(p))return 'Aucune position associée à cette photo.';const source=p.source==='capture'?'Position relevée lors de la capture':p.source==='manual'?'Position associée manuellement':'Position de visite associée (lieu de prise de vue à vérifier)';return `${source} : ${p.lat.toFixed(6)}, ${p.lng.toFixed(6)}${Number.isFinite(p.accuracy)?` · précision ±${Math.round(p.accuracy)} m`:''}`;}
function showPosition(){const p=state.position;$('#geo-status small').textContent=validPosition(p)?`${p.lat.toFixed(6)}, ${p.lng.toFixed(6)} · précision ±${Math.round(p.accuracy||0)} m. Cette position ne modifie pas les anciennes photos.`:'Appuyez pour autoriser la géolocalisation';$('#geo-status').classList.toggle('located',!!p);}
$('#locate-button').addEventListener('click',async()=>{$('#geo-status small').textContent='Recherche de la position…';const p=await requestPosition();if(p){state.position=p;showPosition();saveVisit();}else $('#geo-status small').textContent='Position indisponible ou autorisation refusée.';});
function addPhoto(src,subject,capturedAt,position=null,captureSource='import'){const number=Math.max(0,...state.photos.map(p=>p.number))+1;state.photos.push({id:createId(),number,subject,src,description:'',comment:'',transcript:'',drawing:'',audio:null,capturedAt,captureSource,position,include:{description:true,comment:true,transcript:true,drawing:true}});renderSubjects();renderCaptures();saveVisit();}
async function compressPhoto(src){const image=await loadDrawingImage(src),scale=Math.min(1,1600/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',0.78);}
let importQueue=Promise.resolve();
async function importFiles(files,native=false,subject=state.activeSubject){const time=new Date().toISOString();const positionPromise=native?requestPosition():Promise.resolve(null);let failures=0;for(const file of files){if(!file.type.startsWith('image/')){failures++;continue;}try{const src=await compressPhoto(await readBlob(file));const position=await positionPromise;addPhoto(src,subject,time,position?{...position,source:'capture'}:null,native?'camera':'import');}catch{failures++;}}tell(`${files.length-failures} photo(s) ajoutée(s) et allégée(s) pour ${subject}.${failures?` ${failures} fichier(s) illisible(s) : utilisez JPEG ou PNG.`:''}${!native?' Les photos importées n’ont pas de position connue.':''}`);}
$('#import-photo').addEventListener('click',()=>$('#photo-input').click());
for(const [selector,native] of [['#photo-input',false],['#native-camera',true]])$(selector).addEventListener('change',e=>{const files=[...e.target.files],subject=state.activeSubject;e.target.value='';pendingImports++;importQueue=importQueue.then(()=>importFiles(files,native,subject)).finally(()=>pendingImports--);});
function closeCamera(){++cameraVersion;cameraStream?.getTracks().forEach(t=>t.stop());cameraStream=null;$('#camera-video').srcObject=null;}
$('#photo-button').addEventListener('click',async()=>{const version=++cameraVersion;$('#camera-dialog').showModal();$('#take-photo').disabled=true;$('#camera-status').textContent='Autorisez l’accès à la caméra dans le navigateur.';
  try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('unsupported');const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(version!==cameraVersion||!$('#camera-dialog').open){stream.getTracks().forEach(t=>t.stop());return;}cameraStream=stream;$('#camera-video').srcObject=stream;await $('#camera-video').play();if(version!==cameraVersion)return;$('#take-photo').disabled=false;$('#camera-status').textContent='Cadrez la photo, puis appuyez sur « Prendre la photo ».';}
  catch{$('#camera-status').textContent='Caméra indisponible ou accès refusé. Sur téléphone, essayez le bouton ci-dessous. Sur ordinateur, vérifiez votre webcam ou utilisez « Importer des photos ».';}
});
$('#close-camera').addEventListener('click',()=>$('#camera-dialog').close());$('#camera-dialog').addEventListener('close',closeCamera);
$('#native-camera-button').addEventListener('click',()=>{closeCamera();$('#camera-dialog').close();$('#native-camera').click();});
$('#take-photo').addEventListener('click',async()=>{const video=$('#camera-video');if(!video.videoWidth)return;$('#take-photo').disabled=true;pendingCapture=true;const c=document.createElement('canvas');c.width=video.videoWidth;c.height=video.videoHeight;c.getContext('2d').drawImage(video,0,0);const raw=c.toDataURL('image/jpeg',0.92),subject=state.activeSubject,time=new Date().toISOString(),positionPromise=requestPosition();$('#camera-dialog').close();tell('Photo prise. Réduction de taille et recherche de sa position…');try{const src=await compressPhoto(raw),position=await positionPromise;addPhoto(src,subject,time,position?{...position,source:'capture'}:null,'camera');tell(position?'Photo allégée et position ajoutées. Vous pouvez prendre la suivante pour ce même sujet.':'Photo allégée ajoutée sans position : localisation indisponible.');}catch{tell('La photo n’a pas pu être ajoutée. Réessayez.');}finally{pendingCapture=false;}});
$('#close-audio').addEventListener('click',()=>$('#audio-dialog').close());
function refreshTranscript(photo){$$('[data-photo-id]').filter(c=>c.dataset.photoId===photo.id).forEach(c=>{const field=c.querySelector('[data-edit="transcript"]');if(field&&document.activeElement!==field)field.value=photo.transcript||'';const status=c.querySelector('.transcript-status');if(status)status.textContent=transcriptStatus(photo);});}
function startRecognition(session){
  if(!speechClass)return;const recognition=new speechClass();session.recognition=recognition;recognition.lang='fr-FR';recognition.continuous=true;recognition.interimResults=false;
  const photo=session.photo;photo.transcriptStatus='Transcription en cours…';
  recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)photo.transcript=[photo.transcript,e.results[i][0].transcript.trim()].filter(Boolean).join(' ');refreshTranscript(photo);saveVisit();};
  recognition.onerror=e=>{session.speechError=true;photo.transcriptStatus=`Transcription interrompue (${e.error}). L’audio continue d’être enregistré ; complétez le texte après écoute.`;refreshTranscript(photo);saveVisit();};
  recognition.onend=()=>{if(!session.speechError)photo.transcriptStatus=session.stopping?'Dictée terminée : relisez et complétez le texte.':'La reconnaissance s’est arrêtée ; l’audio continue. Complétez le texte après écoute.';refreshTranscript(photo);saveVisit();};
  try{recognition.start();}catch{session.speechError=true;photo.transcriptStatus='Transcription indisponible. L’audio est enregistré ; saisissez le texte après écoute.';}
}
$('#start-audio').addEventListener('click',async()=>{
  if(recording||!audioTarget)return;const photo=audioTarget,transcribe=$('#transcribe-audio').checked;
  if(photo.audio&&!confirm('Remplacer l’audio existant ? Le texte déjà saisi sera conservé.'))return;
  const session={photo,stopping:false,stream:null,recorder:null};recording=session;$('#audio-dialog').close();$('#recording-status').hidden=false;$('#recording-status span').textContent='Autorisation du microphone…';renderCaptures();
  try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw new Error('unsupported');
    const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(session.stopping){stream.getTracks().forEach(t=>t.stop());recording=null;$('#recording-status').hidden=true;renderCaptures();return;}session.stream=stream;
    const recorder=new MediaRecorder(stream);session.recorder=recorder;const chunks=[];
    recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};
    recorder.onerror=()=>{photo.transcriptStatus='Erreur d’enregistrement. Vérifiez l’audio obtenu.';stopRecording();};
    recorder.onstop=async()=>{session.stopping=true;session.recognition?.stop();stream.getTracks().forEach(t=>t.stop());
      try{const blob=new Blob(chunks,{type:recorder.mimeType||chunks[0]?.type||'audio/webm'});if(!blob.size)throw new Error('empty');photo.audio=await readBlob(blob);if(!photo.transcript)photo.transcriptStatus=transcribe?'Aucun texte reconnu. Écoutez l’audio puis saisissez ou collez sa transcription.':'Audio enregistré sans transcription. Saisissez le texte après écoute si nécessaire.';}
      catch{tell('L’audio n’a pas pu être conservé. Réessayez l’enregistrement.');}
      finally{recording=null;$('#recording-status').hidden=true;renderCaptures();saveVisit();}
    };
    recorder.start(1000);$('#recording-status span').textContent=`● Enregistrement de la photo ${photo.number} en cours`;
    if(transcribe)startRecognition(session);else photo.transcriptStatus='Enregistrement audio seul, sans transcription automatique.';refreshTranscript(photo);
  }catch{session.stream?.getTracks().forEach(t=>t.stop());recording=null;$('#recording-status').hidden=true;renderCaptures();tell('Microphone indisponible ou autorisation refusée. Vérifiez les permissions du navigateur.');}
});
function stopRecording(){if(!recording)return;recording.stopping=true;recording.recognition?.stop();if(recording.recorder?.state==='recording')recording.recorder.stop();$('#recording-status span').textContent='Finalisation de la note…';}
$('#stop-recording').addEventListener('click',stopRecording);
function addAction(values={}){const row=$('#action-template').content.firstElementChild.cloneNode(true);row.querySelector('select').value=values.type||'Créer une tâche';row.querySelector('.action-text').value=values.text||'';row.querySelector('.action-recipient').value=values.recipient||'';row.querySelector('[type="date"]').value=values.date||'';row.querySelector('.remove-action').addEventListener('click',()=>{row.remove();saveVisit();});row.addEventListener('input',saveVisit);$('#action-list').append(row);}
$('#add-action').addEventListener('click',()=>{addAction();saveVisit();});
function collectActions(){return $$('.action-row').map(row=>({type:row.querySelector('select').value,text:row.querySelector('.action-text').value,recipient:row.querySelector('.action-recipient').value,date:row.querySelector('[type="date"]').value}));}
function checkField(photo,field,label,body){return `<section class="review-field"><label class="check-label"><input type="checkbox" data-include="${field}" ${included(photo,field)?'checked':''}> Inclure ${label} dans l’export</label>${body}</section>`;}
function buildReportPreview(){
  $('#summary-editor').innerHTML=state.photos.map(p=>`<article class="summary-card" data-photo-id="${p.id}"><h3>Photo ${p.number} — ${escapeHtml(p.subject)}</h3>${checkField(p,'description','la description',`<label>Description<textarea data-edit="description">${escapeHtml(p.description)}</textarea></label>`)}${checkField(p,'comment','les commentaires',`<label>Commentaires modifiables<textarea data-edit="comment">${escapeHtml(p.comment)}</textarea></label>`)}${checkField(p,'transcript','la transcription',`<p class="transcript-status">${escapeHtml(transcriptStatus(p))}</p><label>Transcription modifiable<textarea data-edit="transcript">${escapeHtml(p.transcript)}</textarea></label>`)}${p.drawing?checkField(p,'drawing','la note manuscrite',`<img class="handwriting-preview" src="${escapeHtml(p.drawing)}" alt="Note manuscrite">`):''}<section class="audio-note"><strong>Audio de la photo ${p.number} — écoute et téléchargement séparé</strong>${audioMarkup(p)}</section></article>`).join('');
  updateReportContent();renderMap();
}
$('#summary-editor').addEventListener('input',e=>{const card=e.target.closest('[data-photo-id]');if(!card)return;const photo=state.photos.find(p=>p.id===card.dataset.photoId);if(e.target.dataset.edit)photo[e.target.dataset.edit]=e.target.value;if(e.target.dataset.include){photo.include||={};photo.include[e.target.dataset.include]=e.target.checked;}updateReportContent();saveVisit();});
function reportPhotoHtml(photo){const text=(field,label)=>included(photo,field)&&photo[field]?.trim()?`<p><strong>${label}</strong><br>${escapeHtml(photo[field]).replace(/\n/g,'<br>')}</p>`:'';return `<article><div class="report-image"><img src="${escapeHtml(photo.reportSrc||photo.annotatedSrc||photo.src)}" width="240" height="125" style="width:240px;height:125px;object-fit:contain" alt="Photo ${photo.number}"></div><h4>Photo ${photo.number}</h4>${text('description','Description')}${text('comment','Commentaires')}${text('transcript','Transcription')}${included(photo,'drawing')&&photo.drawing?`<img class="report-drawing" src="${escapeHtml(photo.drawing)}" width="240" style="width:240px;height:auto" alt="Note manuscrite">`:''}</article>`;}
function groupedReportHtml(){return state.subjects.map(subject=>{const photos=state.photos.filter(p=>p.subject===subject);if(!photos.length)return '';const rows=[];for(let i=0;i<photos.length;i+=2)rows.push(`<tr><td width="50%">${reportPhotoHtml(photos[i])}</td><td width="50%">${photos[i+1]?reportPhotoHtml(photos[i+1]):''}</td></tr>`);return `<section class="report-subject"><h3>${escapeHtml(subject)} — ${photos.length} photo(s)</h3><table class="report-table" width="100%"><tbody>${rows.join('')}</tbody></table></section>`;}).join('');}
function reportActionsHtml(){const actions=collectActions().filter(a=>a.text.trim()||a.recipient.trim());return actions.length?`<h3>Suites à donner</h3><ul>${actions.map(a=>`<li><strong>${escapeHtml(a.type)}</strong> — ${escapeHtml(a.text)}${a.recipient?` · Destinataire : ${escapeHtml(a.recipient)}`:''}${a.date?` · Échéance : ${escapeHtml(a.date)}`:''}</li>`).join('')}</ul>`:'';}
function updateReportContent(){$('#report-date').textContent=new Date().toLocaleDateString('fr-FR');const selected=$$('.case-option')[state.caseIndex];$('.report-top small').textContent=selected?`${selected.querySelector('small').textContent} — ${selected.querySelector('b').textContent}`:'';$('#report-photos').innerHTML=groupedReportHtml()||'<p>Aucune photo.</p>';$('#report-actions').innerHTML=reportActionsHtml();}
function osmLink(p){return `https://www.openstreetmap.org/?mlat=${p.lat}&mlon=${p.lng}#map=18/${p.lat}/${p.lng}`;}
function renderMap(){const points=state.photos.filter(p=>validPosition(p.position)),visit=validPosition(state.position);if(!points.length&&!visit){$('#map-points').innerHTML='<p>Aucune photo localisée. Dans la collecte, utilisez « Associer la position actuelle à cette photo » si vous êtes sur place.</p>';return;}$('#map-points').innerHTML=`<label>Emplacement affiché<select id="map-selection">${points.map(p=>`<option value="${p.id}">Photo ${p.number} — ${escapeHtml(p.subject)}</option>`).join('')}${visit?'<option value="visit">Position de la visite (pas une prise de vue)</option>':''}</select></label><p id="map-caption"></p><iframe id="osm-map" title="Carte OpenStreetMap de l’emplacement sélectionné" loading="lazy"></iframe><a id="osm-link" target="_blank" rel="noopener">Ouvrir cette position dans OpenStreetMap</a><p>© contributeurs OpenStreetMap · Un repère à la fois ; changez de photo dans la liste.</p>`;$('#map-selection').addEventListener('change',updateMap);updateMap();}
function updateMap(){const choice=$('#map-selection').value,photo=state.photos.find(p=>p.id===choice),p=photo?.position||state.position,delta=0.002;const bbox=[Math.max(-180,p.lng-delta),Math.max(-90,p.lat-delta),Math.min(180,p.lng+delta),Math.min(90,p.lat+delta)].join(',');$('#osm-map').src=`https://www.openstreetmap.org/export/embed.html?bbox=${encodeURIComponent(bbox)}&layer=mapnik&marker=${p.lat}%2C${p.lng}`;$('#osm-link').href=osmLink(p);$('#map-caption').textContent=photo?`Photo ${photo.number} — ${locationLabel(photo)}`:'Position de visite uniquement. Elle n’est pas attribuée automatiquement aux photos importées.';}
function reportLocationsHtml(){const points=state.photos.filter(p=>validPosition(p.position));return points.length?`<h3>Emplacements des prises de vue</h3><ul>${points.map(p=>`<li>Photo ${p.number} — ${escapeHtml(locationLabel(p))} — <a href="${osmLink(p.position)}">Voir sur OpenStreetMap</a></li>`).join('')}</ul>`:'<p>Aucune position de prise de vue enregistrée.</p>';}
function download(blob,name){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function exportHtml(){const heading=$('.report-top').innerHTML;return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><style>@page{size:A4 portrait;margin:1.8cm}body{font-family:Arial;font-size:12pt}table{width:100%;table-layout:fixed;border-collapse:collapse}td{width:50%;vertical-align:top;padding:8pt;border:1px solid #ddd;white-space:normal}tr{page-break-inside:avoid}h3{page-break-after:avoid}img{max-width:240px}p{line-height:1.35;word-wrap:break-word}h4{margin:6pt 0}.report-image{text-align:center}</style></head><body>${heading}${groupedReportHtml()}${reportActionsHtml()}${reportLocationsHtml()}</body></html>`;}
$('#generate-report').addEventListener('click',async()=>{const button=$('#generate-report');button.disabled=true;try{for(const p of state.photos){const img=await loadDrawingImage(p.annotatedSrc||p.src),c=document.createElement('canvas');c.width=480;c.height=250;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,480,250);const scale=Math.min(480/img.naturalWidth,250/img.naturalHeight);ctx.drawImage(img,(480-img.naturalWidth*scale)/2,(250-img.naturalHeight*scale)/2,img.naturalWidth*scale,img.naturalHeight*scale);p.reportSrc=c.toDataURL('image/jpeg',0.9);}updateReportContent();download(new Blob([exportHtml()],{type:'application/msword'}),'reportage-photographique.doc');$('.toast').textContent='Rapport téléchargé : uniquement les éléments cochés.';$('.toast').classList.add('show');setTimeout(()=>$('.toast').classList.remove('show'),4000);}catch{alert('Une photo n’a pas pu être préparée pour le rapport. Vérifiez les images de la collecte.');}finally{state.photos.forEach(p=>delete p.reportSrc);button.disabled=false;}});
const database=new Promise(resolve=>{if(!window.indexedDB){resolve(null);return;}try{const req=indexedDB.open('constat-visits'+(TEST_MODE?'-verification':''),2);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('visits'))req.result.createObjectStore('visits');if(!req.result.objectStoreNames.contains('drafts'))req.result.createObjectStore('drafts');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null);req.onblocked=()=>resolve(null);}catch{resolve(null);}});
async function dbRead(){const db=await database;if(!db)return null;return new Promise((resolve,reject)=>{const request=db.transaction('visits').objectStore('visits').get('current');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
async function dbWrite(value){const db=await database;if(!db){localStorage.setItem(STORAGE_KEY,JSON.stringify(value));localStorage.setItem(STORAGE_KEY+'-draft-'+value.draftId,JSON.stringify(value));return;}return new Promise((resolve,reject)=>{const tx=db.transaction(['visits','drafts'],'readwrite');tx.objectStore('visits').put(value,'current');tx.objectStore('drafts').put(value,value.draftId);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function snapshot(){state.draftId||=createId();return {version:2,draftId:state.draftId,savedAt:new Date().toISOString(),subjects:[...state.subjects],activeSubject:state.activeSubject,photos:structuredClone(state.photos).map(p=>{delete p.reportSrc;return p;}),position:state.position,actions:collectActions(),caseIndex:state.caseIndex};}
function saveVisit(){if(!ready)return;unsaved=true;++revision;updateSaveState('Enregistrement…');clearTimeout(saveTimer);saveTimer=setTimeout(persistVisit,300);}
function persistVisit(){if(!ready)return Promise.resolve();clearTimeout(saveTimer);const version=revision,value=snapshot();saveQueue=saveQueue.catch(()=>{}).then(()=>dbWrite(value)).then(()=>{if(version===revision){unsaved=false;updateSaveState('✓ Brouillon enregistré sur cet appareil');}renderDrafts();return true;}).catch(()=>{updateSaveState('Échec de sauvegarde : conservez une copie avec « Sauvegarder la visite dans un fichier ».',true);return false;});return saveQueue;}
function normalizeVisit(saved){if(!saved||!Array.isArray(saved.photos)||!Array.isArray(saved.subjects))throw new Error('invalid');const result={...saved,subjects:[...new Set(saved.subjects.filter(s=>typeof s==='string'&&s.trim()).map(s=>s.slice(0,160)))]};if(!result.subjects.length)result.subjects=['Vue générale'];const ids=new Set(),numbers=new Set();result.photos=saved.photos.map((p,i)=>{if(!p||typeof p.src!=='string'||!/^data:image\/(jpeg|png|webp|gif|bmp|avif);/i.test(p.src))throw new Error('invalid image');const photo={id:typeof p.id==='string'&&/^[\w-]+$/.test(p.id)&&!ids.has(p.id)?p.id:createId(),number:Number.isInteger(p.number)&&p.number>0&&!numbers.has(p.number)?p.number:i+1,src:p.src,subject:typeof p.subject==='string'?p.subject.slice(0,160):result.subjects[0],position:validPosition(p.position)?p.position:null,capturedAt:p.capturedAt,captureSource:p.captureSource,include:{...p.include}};while(numbers.has(photo.number))photo.number++;ids.add(photo.id);numbers.add(photo.number);for(const key of ['description','comment','transcript','transcriptStatus'])photo[key]=typeof p[key]==='string'?p[key]:'';for(const key of ['drawing','annotatedSrc'])photo[key]=typeof p[key]==='string'&&/^data:image\/(jpeg|png|webp);/i.test(p[key])?p[key]:'';photo.audio=typeof p.audio==='string'&&/^data:(audio\/|video\/webm)/i.test(p.audio)?p.audio:null;if(!result.subjects.includes(photo.subject))result.subjects.push(photo.subject);return photo;});result.position=validPosition(saved.position)?saved.position:null;result.actions=Array.isArray(saved.actions)?saved.actions:[];return result;}
function restoreState(value){const saved=normalizeVisit(value);state.draftId=typeof saved.draftId==='string'?saved.draftId:createId();state.subjects=saved.subjects;state.activeSubject=state.subjects.includes(saved.activeSubject)?saved.activeSubject:state.subjects[0];state.photos=saved.photos;state.position=saved.position;selectCase(Number.isInteger(saved.caseIndex)&&saved.caseIndex>=0&&saved.caseIndex<$$('.case-option').length?saved.caseIndex:0);$('#action-list').innerHTML='';saved.actions.forEach(addAction);if(!$('.action-row'))addAction();renderSubjects();renderCaptures();showPosition();if(state.currentStep===4)buildReportPreview();}
$('#backup-visit').addEventListener('click',()=>{if(recording){alert('Arrêtez l’enregistrement avant de sauvegarder la visite.');return;}download(new Blob([JSON.stringify(snapshot())],{type:'application/json'}),'constat-sauvegarde.json');});
$('#restore-visit').addEventListener('click',()=>{if(recording){alert('Arrêtez l’enregistrement avant d’ouvrir une autre visite.');return;}$('#backup-input').click();});
$('#backup-input').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{const saved=normalizeVisit(JSON.parse(await file.text()));if(state.photos.length&&!confirm('Remplacer la visite affichée par cette sauvegarde ? Conservez d’abord une copie si nécessaire.'))return;restoreState(saved);saveVisit();}catch{alert('Ce fichier n’est pas une sauvegarde Constat valide. La visite actuelle est conservée.');}});
window.addEventListener('beforeunload',e=>{if(unsaved||recording){e.preventDefault();e.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&unsaved)persistVisit();});
async function initialize(){document.body.classList.add('loading-visit');let saved,restored=false;try{saved=await dbRead();if(!saved){const legacy=localStorage.getItem(STORAGE_KEY);if(legacy)saved=JSON.parse(legacy);}if(saved){restoreState(saved);restored=true;updateSaveState('✓ Visite restaurée sur cet appareil');}}catch{updateSaveState('La sauvegarde n’a pas pu être lue. Conservez votre ancienne version.',true);}finally{if(!$('.action-row'))addAction();renderSubjects();renderCaptures();showPosition();ready=true;document.body.classList.remove('loading-visit');if(restored)saveVisit();renderDrafts();}}
